### ISSUE TITLE
Support lookup within map

### ISSUE THREAD

**Issue by Undistraction** [jaicab/sass-vary#11]
It is probably worth considering allowing one key in a vary map to reference another key. This could be done with a token:

( primary-color: #FF000,
  secondary-color: #00FF00,
  button-color: '#{primary-color}',
  tab-color: '#{primary-color}',
  button-secondary-color: '#{primary-color}');

I guess this is related to #10 in terms of how flexible should Vary be.

**Comment by jaicab** [comment]
This is definitely a no from me. I'll leave this open in case somebody agrees and then may reconsider. I think you should use primary color in the element you're targeting instead.
Not to mention the possibility of adding nested maps. This could get crazy.

**Comment by jaicab** [comment]
Now I think of it, I reckon this is impossible without using some kind of vary's internal wrapper that was replaced with a value afterwards. But ideally you would want to use `vary-get` to access them.

```
$vary-map: (
  user: (
    'color-primary': red,
    'color-secondary': blue
    'button-color': vary-get('color-primary')
  ),
);
```

Right now, this would result into `button-color` having a value of "vary-get('color-primary')". The value of every element should be checked with `vary-get` and be called recursively with those values. Very difficult thing to do and pretty sure could become counterproductive. 

The idea of having a value declared only once is one of the main points of using vary.

**Comment by Undistraction** [comment]
Sorry. My pseudo-code was crap. I didn't intend that the `#{}` would be parsed by Sass as a token, just that it represented some kind of delimited string. As you rightly point out, the lookup can't occur at the point the map is declared. So some kind of delimiter that Vary recognises could be used instead. That way, if vary encounters a delimited string for the key value (perhaps '[something-delimited-by-hard-brackets]'), it knows to look that string up as if it was a new key.

**Comment by jaicab** [comment]
After giving this some thought, I'm certain this could get messy and difficult to maintain. No matter what kind of wrapper we use, there are two issues when picking a delimiter:
- If somebody actually wants those in a string, they would need to escape them. Too messy.
- As the Sass spec evolves, there may be collisions between this and the one used on new versions.

Maintaining this feature is something I really don't want to deal with, not to mention it is against the idea of over-specifying values which prevention motivated the creation of vary. So even though I could include the feature and just recommend not use it, I don't feel it is correct to do so.

If anybody else wants to fork vary and implement this feature, please feel free.
