### ISSUE TITLE
Allow customisable default argument create argument of vary

### ISSUE THREAD

**Issue by Undistraction** [jaicab/sass-vary#5]
If I'm a heavy user of BEM-style selectors, allow me to set the default for the create argument of the `vary` mixin, rather than having to hardcode it everywhere:

```
$vary-default-create: 'mod'.

@include vary() {}
```

In fact choosing a default value anyway wouldn't be a bad idea.

**Comment by jaicab** [comment]
That was an option on the first versions as [$vary-default-action](https://github.com/jaicab/sass-vary/commit/37728587bea01f3757457aec087874aaa0f58255), but I removed it because:
- When people that tried it faced a different scenario (like the body class one) they didn't even know it was a possibility to change the creation mode.
- I found that half the people used the body approach while the other half used the BEM approach. Setting a default option turned out to be more confusing as it didn't do what they expected to do. That's also the reason I didn't add a default value.

It may be added on version 1.1 with a different approach, as an added option but not the recommended use by default.

**Comment by Undistraction** [comment]
> When people that tried it faced a different scenario (like the body class one) they didn't even know it was a possibility to change the creation mode.

I have to say, I think this is the job of docs (and yours are pretty good). You could still continue to explicity pass the default in your docs to make it clear that there is a (varying) parameter.

> I found that half the people used the body approach while the other half used the BEM approach. Setting a default option turned out to be more confusing as it didn't do what they expected to do. That's also the reason I didn't add a default value.

I have to say, I think the naming of the different output strategies is really confusing. Using the name `body` is definitely a mistake as `body` already has such strong associations with the html `body` element. This is compounded by the naming of the second strategy as `html-body`. Every lib has a knot of complexity and this is yours - It's really nicely thought out, but the naming needs to be revisited imho.

**Comment by jaicab** [comment]
> I have to say, I think this is the job of docs (and yours are pretty good). You could still continue to explicity pass the default in your docs to make it clear that there is a (varying) parameter.

Totally agree with you on that. As I said, the default option will be included in the next version with a different approach, including the create parameter defined in the demos (as you recommend) but giving the option to set a default. What I haven't yet considered is wether to define it with a value or not by default.

> I have to say, I think the naming of the different output strategies is really confusing. Using the name body is definitely a mistake as body already has such strong associations with the html body element. This is compounded by the naming of the second strategy as html-body. Every lib has a knot of complexity and this is yours - It's really nicely thought out, but the naming needs to be revisited imho.

I tried my best with naming. I know it's not great, but they're simple and easy to remember. I want people that have never done an each loop in Sass could work with vary from day one.

I checked with the frontend team at Base and they couldn't come up with a better keyword either. Using numbers (e.g. 1, 2, 3, etc) didn't make sense at all and making it longer (e.g. html-class-wrapper-bodyclass) just made it more painful and difficult to use. 

I will give it some more thought but I reckon it's not easy. But hey, feel free too open an issue with any other naming ideas!

**Comment by Undistraction** [comment]
Let me have a play and if I can do any better I will make a suggestion.

Naming is (almost) always the hardest thing, but worth the time spent. Numbers are a definite no, but I personally wouldn't be afraid of slightly more verbose / descriptive names. Especially if you can set them a single time as a default. Even without defaults, I'd always take a few extra keystrokes over a more obscure name that makes you stop and think every time you come to remember and type it.

**Comment by jaicab** [comment]
Feature included on [vary 1.1](https://github.com/jaicab/sass-vary/releases) :+1:

**Comment by Undistraction** [comment]
Nice work.
