### ISSUE TITLE
Ideas for more representative $create keywords

### ISSUE THREAD

**Issue by jaicab** [jaicab/sass-vary#6]
Aware of the possible confusion with the current keywords for `$create` (`body`, `htmlbody`, `mod` and `custom`) and seeing the [feedback](https://github.com/jaicab/sass-vary/issues/5#issuecomment-108017323), it would be good to come up with more representative keywords for the `$create` parameter.

Feel free to comment any ideas for keywords you may have and I'll pick the ones that people like the most. Keep in mind that they need to be scalable as more creation methods may be added in the future.

**Comment by Undistraction** [comment]
`body` is really just appending a parent class to the supplied selectors, so maybe `parent`. This would allow `htmlbody` to become just `html` which is fine as it explicitly adds the supplied selectors to the `html` element selector. `mod` is OK, but `modifier` is much clearer.

**Comment by indrekpaas** [comment]
> `body` is really just appending a parent class to the supplied selectors, so maybe `parent`. This would allow `htmlbody` to become just `html` which is fine as it explicitly adds the supplied selectors to the `html` element selector. `mod` is OK, but `modifier` is much clearer.

I agree, very self-explanatory. I'd also add some simple sort of keyword validation not to have the mixin fail silently producing unexpected results.

**Comment by jaicab** [comment]
Ok, I like the idea of using `parent` and `modifier`, but `html` needs to change. What it does is that it puts the body class right after the first selector which has to be an HTML class. That's why I used `htmlbody`. So in this example: 

``` sass
.js .foo{
    background: red;

    @include vary($create: htmlbody) {
        background: vary-get('color-primary');
    }
}
```

Notice how vary puts the body class right after the first selector (`.js`):

``` css
.foo{
    background: red;    
}

html.js .is-user .foo{
    background: blue;
}

html.js .is-admin .foo{
    background: pink;
}

html.js .is-superadmin .foo{
    background: black;
}
```

**Note**: Remember that the `html` tag is just there for libsass support, focus on the `.is-foo` class here.

In my opinion, the `html` one must be more descriptive, as it does not add the class to the html element but just places the body class between the html class and the rest of selectors.

Regarding the validation @indrekpaas, very good plan. Also vary 1.1 will bring back the default creation mode as it's being discussed on #5.

**Comment by Undistraction** [comment]
> it does not add the class to the html element but just places the body class between the html class and the rest of selectors.

How about calling it `insert` or maybe `wrap`.

**Comment by jaicab** [comment]
Ok, so I've been giving this some thought and I'm sure `parent` and `modifier` are final.

For the `html` one, not so sure. `wrap` could be confused with `parent` and `insert` is too close to other behaviors that could come up in the future, like the new [combine](https://github.com/jaicab/sass-vary/issues/7). I knew these keywords had to change but for maintenance reasons it wouldn't be good to change them more than once. 

I'll give it some more thought and if nothing else has come up by Saturday I think I'll use `html` but explain it differently on the site, and the same with `parent`.

**Comment by Undistraction** [comment]
I would maybe go with _append_ rather than _combine_, as combine is very general. 

Maybe the best way to decide on names is to make sure they all describe the same kind of thing. It looks like the names of the create mode are describing how/where the class is added. This might mean that _append_ might actually be a better name for _modifier_ and _insert_ might be a better name for _html-body_ . guess the important thing is they all feel like part of a set. Much easier to mentally model.

**Comment by Undistraction** [comment]
I would maybe go with *append* rather than *combine*, as combine is very
general.

**Comment by jaicab** [comment]
Ok so [vary 1.1 is out](https://github.com/jaicab/sass-vary/releases/tag/1.1) and here are the changes on keywords for `$create`:
- `body` becomes `parent`.
- `htmlbody` becomes `insert`.
- `mod` becomes `modifier`.
- `custom` stays unaltered.
- New creation mode `append` which appends a class (#7).

I like to keep modifier to make it clear it's BEM-related, even though it may be similar to append.
